# Generated by Django 3.2 on 2021-04-29 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=32)),
                ('nivel', models.CharField(max_length=8)),
                ('goles', models.IntegerField()),
                ('sueldo', models.FloatField()),
                ('bono', models.FloatField()),
                ('sueldo_completo', models.FloatField(blank=True, null=True)),
                ('equipo', models.CharField(blank=True, max_length=15, null=True)),
            ],
        ),
    ]
