# Generated by Django 3.2 on 2021-04-29 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('player', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='player',
            name='equipo',
            field=models.CharField(max_length=15),
        ),
    ]
